### ISSUE TITLE
bar disappears when value>100

### ISSUE THREAD

**Issue by nebulous** [cdjackson/angular-dialgauge#7]
Example in this fiddle: http://jsfiddle.net/7qq1keyL/

with scaleMax set to 1000, the display bar is properly scaled, but disappears with values greater than 100.

**Comment by garfield69** [comment]
It's something to do with your bar color. For instance, if you change to `bar-color="#FF0000"` then gauge2 shows your value.
[edit] found a bug in the color gradient logic. if pull request #8 is accepted then this should solve your issue.

**Comment by nebulous** [comment]
Thanks @garfield69 your patch to divide by the scale rather than 100 worked nicely. I'm sure @cdjackson will apply it when he gets the time.

**Comment by cdjackson** [comment]
Thanks guys - sorry this took a while, I'm super busy at the moment.
